# Auto-generated from bookr_compliance_calendar_v7.html CORE_TASKS array.
# Each dict seeds one row in the tasks table on first startup (see main.py lifespan).
CORE_TASKS = [
    {'key': '1099nec', 'num': 1, 'quarter': 'Q1', 'scope': 'Federal', 'short': '1099-NEC', 'title': 'Form 1099-NEC Filing & Distribution', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Bookr, Inc.', 'portal_name': 'IRS FIRE System', 'portal_url': 'https://fire.irs.gov/', 'alt_note': 'Can also be filed directly through payroll software such as Gusto or Rippling.', 'info': 'Required only if Bookr paid an unincorporated contractor, freelancer, or unincorporated LLC $600 or more in the prior calendar year via ACH, check, or wire. Pebble LLC is paid by company credit card, so Pebble is exempt regardless of amount. Confirm against your actual vendor payment ledger.'},
    {'key': 'w2w3', 'num': 2, 'quarter': 'Q1', 'scope': 'Federal', 'short': 'W-2 / W-3', 'title': 'Wage and Tax Statements (Forms W-2 & W-3)', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Bookr, Inc.', 'portal_name': 'SSA Business Services Online', 'portal_url': 'https://www.ssa.gov/bso', 'alt_note': 'Managed comprehensively through your integrated Gusto workspace platform configurations.', 'info': 'Applies — public listings put Bookr at roughly 11–60 W-2 employees, so this filing is live every year. The W-2 reports individual employee earnings/withholdings; the W-3 is the master transmittal filed with SSA.'},
    {'key': '941q4', 'num': 3, 'quarter': 'Q1', 'scope': 'Federal', 'short': '941 Q4', 'title': 'Federal Employer’s Quarterly Tax Return (Form 941) — Q4 filing', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Gusto automated scheduling runs this background process pipeline cleanly.', 'info': 'Reconciles federal income tax withholding plus Social Security and Medicare tax for Q4. Bookr has no proprietary software engineering function, so Line 11 stays blank — no R&D payroll tax offset applies.'},
    {'key': '940', 'num': 4, 'quarter': 'Q1', 'scope': 'Federal', 'short': '940 FUTA', 'title': 'Federal Annual Unemployment Tax Return (Form 940)', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Handled natively by payroll processing parameters within Gusto.', 'info': 'Assesses FUTA liability on the first $7,000 paid to each individual W-2 employee for the year. Applies given Bookr’s active payroll.'},
    {'key': 'de9q4', 'num': 5, 'quarter': 'Q1', 'scope': 'California', 'short': 'DE 9/9C Q4', 'title': 'CA EDD Quarterly Payroll Returns (DE 9 & DE 9C) — Q4 filing', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Bookr, Inc.', 'portal_name': 'CA EDD e-Services for Business', 'portal_url': 'https://eddservices.edd.ca.gov/', 'alt_note': 'Gusto updates status parameter arrays automatically.', 'info': 'DE 9 reconciles total state payroll tax; DE 9C reports individual employee wage and SDI detail. Applies — Bookr is headquartered and staffed in California.'},
    {'key': 'defranchise', 'num': 6, 'quarter': 'Q1', 'scope': 'Delaware', 'short': 'DE Franchise Tax', 'title': 'Delaware Annual Franchise Tax & Report', 'due_type': 'fixed', 'due_month': 3, 'due_day': 1, 'due_text': 'March 1', 'entity': 'Bookr, Inc. (DE)', 'portal_name': 'Delaware Division of Corporations — eCorp', 'portal_url': 'https://icis.corp.delaware.gov/Ecorp/LoginTax.aspx?FilingType=FranchiseTax', 'alt_note': None, 'info': 'Confirmed applicable: Bookr’s CA Secretary of State record lists "Formed In: Delaware," meaning it is a Delaware corporation foreign‑qualified in California. Use the Assumed Par Value Capital Method for the lowest tier. $50 filing fee + $400 minimum tax.'},
    {'key': '571l', 'num': 7, 'quarter': 'Q2', 'scope': 'California', 'short': '571-L', 'title': 'California Business Property Statement (Form 571-L)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 1, 'due_text': 'April 1', 'entity': 'Bookr, Inc.', 'portal_name': 'Contra Costa County Assessor — e-SDR', 'portal_url': 'https://www.contracosta.ca.gov/5498/Business-Personal-Property-e-File', 'alt_note': None, 'info': 'A 10% late penalty applies if not filed/postmarked by May 7. Only required if unsecured business personal property (servers, furniture, computers) at the Walnut Creek office totals $100,000+ in historical cost.'},
    {'key': '1120', 'num': 8, 'quarter': 'Q2', 'scope': 'Federal', 'short': 'Form 1120', 'title': 'U.S. Corporation Income Tax Return (Form 1120)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'April 15', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS (payment)', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Can be extended six months to October 15 by filing Form 7004 before this date.', 'info': 'Core federal income tax return — always applies to a C-corp. Tracks service revenue from non-profit clients minus operating costs; vendor platform subscription fees are deducted as ordinary business deductions.'},
    {'key': 'ftb100', 'num': 9, 'quarter': 'Q2', 'scope': 'California', 'short': 'FTB Form 100', 'title': 'CA Corporation Franchise & Income Tax Return (FTB Form 100)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'April 15', 'entity': 'Bookr, Inc.', 'portal_name': 'FTB Web Pay for Businesses', 'portal_url': 'https://webapp.ftb.ca.gov/webpay/login/belogin', 'alt_note': 'California grants an automatic paperwork extension to November 15, but any tax owed must still be paid by April 15.', 'info': 'Confirmed applicable — Bookr’s public filing record shows Franchise Tax Board standing as "Good." Assesses CA’s flat 8.84% rate on income apportioned to the state. The $800 annual minimum franchise tax is due every year.'},
    {'key': 'fed1120w1', 'num': 10, 'quarter': 'Q2', 'scope': 'Federal', 'short': '1120-W #1', 'title': 'Federal Quarterly Estimated Income Tax (Form 1120-W) — Installment 1', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'April 15', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Required once Bookr anticipates annual federal corporate income tax liability of $500 or more.'},
    {'key': 'ca100es1', 'num': 11, 'quarter': 'Q2', 'scope': 'California', 'short': '100-ES #1', 'title': 'California Corporate Estimated Tax (Form 100-ES) — Installment 1', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'April 15', 'entity': 'Bookr, Inc.', 'portal_name': 'FTB Web Pay for Businesses', 'portal_url': 'https://webapp.ftb.ca.gov/webpay/login/belogin', 'alt_note': None, 'info': 'California uses an uneven schedule — this first installment must cover 30% of estimated annual state tax.'},
    {'key': '941de9q1', 'num': 12, 'quarter': 'Q2', 'scope': 'Federal', 'short': '941 / DE9 Q1', 'title': 'Form 941 & CA EDD DE 9/9C — Q1 filing', 'due_type': 'fixed', 'due_month': 4, 'due_day': 30, 'due_text': 'April 30', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS / CA EDD e-Services', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Processed in full through dynamic backend actions in Gusto.', 'info': 'Regular quarterly reporting of Q1 employee payroll withholdings and matching corporate payroll taxes.'},
    {'key': 'fed1120w2', 'num': 13, 'quarter': 'Q2', 'scope': 'Federal', 'short': '1120-W #2', 'title': 'Federal Quarterly Estimated Income Tax (Form 1120-W) — Installment 2', 'due_type': 'fixed', 'due_month': 6, 'due_day': 15, 'due_text': 'June 15', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Second quarterly installment of estimated federal corporate income tax.'},
    {'key': 'ca100es2', 'num': 14, 'quarter': 'Q2', 'scope': 'California', 'short': '100-ES #2', 'title': 'California Corporate Estimated Tax (Form 100-ES) — Installment 2', 'due_type': 'fixed', 'due_month': 6, 'due_day': 15, 'due_text': 'June 15', 'entity': 'Bookr, Inc.', 'portal_name': 'FTB Web Pay for Businesses', 'portal_url': 'https://webapp.ftb.ca.gov/webpay/login/belogin', 'alt_note': None, 'info': 'This second installment must cover 40% of estimated annual state tax.'},
    {'key': '941de9q2', 'num': 15, 'quarter': 'Q3', 'scope': 'Federal', 'short': '941 / DE9 Q2', 'title': 'Form 941 & CA EDD DE 9/9C — Q2 filing', 'due_type': 'fixed', 'due_month': 7, 'due_day': 31, 'due_text': 'July 31', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS / CA EDD e-Services', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Automated framework updates managed via Gusto accounts.', 'info': 'Regular quarterly reporting of Q2 employee payroll withholdings and matching corporate payroll taxes.'},
    {'key': 'fed1120w3', 'num': 16, 'quarter': 'Q3', 'scope': 'Federal', 'short': '1120-W #3', 'title': 'Federal Quarterly Estimated Income Tax (Form 1120-W) — Installment 3', 'due_type': 'fixed', 'due_month': 9, 'due_day': 15, 'due_text': 'September 15', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Third quarterly installment of estimated federal corporate income tax.'},
    {'key': 'ca100es3', 'num': 17, 'quarter': 'Q3', 'scope': 'California', 'short': '100-ES #3', 'title': 'California Corporate Estimated Tax (Form 100-ES) — Installment 3', 'due_type': 'fixed', 'due_month': 9, 'due_day': 15, 'due_text': 'September 15', 'entity': 'Bookr, Inc.', 'portal_name': 'FTB Web Pay for Businesses', 'portal_url': 'https://webapp.ftb.ca.gov/webpay/login/belogin', 'alt_note': None, 'info': 'Under California’s staggered model this installment’s allocation is 0% — no payment due — provided the prior installments were paid.'},
    {'key': '941de9q3', 'num': 18, 'quarter': 'Q4', 'scope': 'Federal', 'short': '941 / DE9 Q3', 'title': 'Form 941 & CA EDD DE 9/9C — Q3 filing', 'due_type': 'fixed', 'due_month': 10, 'due_day': 31, 'due_text': 'October 31', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS / CA EDD e-Services', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Corporate updates deployed to state agencies through Gusto pipelines.', 'info': 'Regular quarterly reporting of Q3 employee payroll withholdings and matching corporate payroll taxes.'},
    {'key': 'fed1120w4', 'num': 19, 'quarter': 'Q4', 'scope': 'Federal', 'short': '1120-W #4', 'title': 'Federal Quarterly Estimated Income Tax (Form 1120-W) — Installment 4', 'due_type': 'fixed', 'due_month': 12, 'due_day': 15, 'due_text': 'December 15', 'entity': 'Bookr, Inc.', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Fourth and final quarterly installment of estimated federal corporate income tax.'},
    {'key': 'ca100es4', 'num': 20, 'quarter': 'Q4', 'scope': 'California', 'short': '100-ES #4', 'title': 'California Corporate Estimated Tax (Form 100-ES) — Installment 4', 'due_type': 'fixed', 'due_month': 12, 'due_day': 15, 'due_text': 'December 15', 'entity': 'Bookr, Inc.', 'portal_name': 'FTB Web Pay for Businesses', 'portal_url': 'https://webapp.ftb.ca.gov/webpay/login/belogin', 'alt_note': None, 'info': 'Covers the remaining 30% allocation of estimated annual California corporate tax.'},
    {'key': 'si550', 'num': 21, 'quarter': 'ROLL', 'scope': 'California', 'short': 'Form SI-550', 'title': 'California Statement of Information (Form SI-550)', 'due_type': 'fixed', 'due_month': 8, 'due_day': 31, 'due_text': 'August 31 (anniversary month)', 'entity': 'Bookr, Inc.', 'portal_name': 'CA Secretary of State — bizfile Online', 'portal_url': 'https://bizfileonline.sos.ca.gov/', 'alt_note': None, 'info': 'Confirmed from Bookr’s public SOS record: late August is the real annual deadline. Filing fee $25. Missing it triggers an automatic $250 penalty.'},
    {'key': 'wcbiz', 'num': 22, 'quarter': 'ROLL', 'scope': 'California', 'short': 'WC Business License', 'title': 'City of Walnut Creek Business Tax Certificate (Business License)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — due on the last day of the month before expiration.', 'entity': 'Bookr, Inc.', 'portal_name': 'Walnut Creek HdLgov Business Portal', 'portal_url': 'https://walnutcreek.hdlgov.com/', 'alt_note': None, 'info': 'Confirmed applicable — Bookr’s headquarters at 2099 Mt. Diablo Blvd is inside Walnut Creek city limits. Missing renewal triggers an immediate 25% penalty.'},
    {'key': 'formalities', 'num': 23, 'quarter': 'ROLL', 'scope': 'Internal', 'short': 'Corp Formalities', 'title': 'Mandatory Annual Corporate Formalities', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — best practice is to finalize within 5 months of fiscal year close.', 'entity': 'Bookr, Inc.', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'To preserve the corporate veil, Bookr must execute Unanimous Written Consents for Shareholders and Directors (Officers: Girish Dinakaran, James Munch), then store both in the Corporate Minute Book.'},
    {'key': 'regagent', 'num': 24, 'quarter': 'ROLL', 'scope': 'Delaware', 'short': 'Registered Agent', 'title': 'Registered Agent Annual Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, on the service provider’s contract anniversary date.', 'entity': 'Bookr, Inc. (DE)', 'portal_name': 'EntityCompli / Vcorp Portal', 'portal_url': 'https://www.entitycompli.com/', 'alt_note': None, 'info': 'Confirmed — Bookr’s public SOS record lists Vcorp Agent Services, Inc. as registered agent. Non-payment causes the agent to resign.'},
    {'key': 'idmsosca', 'num': 25, 'quarter': 'ROLL', 'scope': 'California', 'short': 'CA SoS IDM', 'title': 'CA Secretary of State Identity Management Portal Access', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Continuous account management.', 'entity': 'All Entities', 'portal_name': 'idm.sos.ca.gov', 'portal_url': 'https://idm.sos.ca.gov/signin/register', 'alt_note': None, 'info': 'Master CA SoS Identity Management credential system registration. Used to manage state-level organizational filing identities across all operational corporate structures.'},
    {'key': 'everify', 'num': 26, 'quarter': 'ROLL', 'scope': 'Federal', 'short': 'E-Verify USCIS', 'title': 'E-Verify USCIS New Hire Verification Enrollment Protocol', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Mandated for compliance upon onboarding new individuals.', 'entity': 'Bookr, Inc.', 'portal_name': 'idp.uscis.gov', 'portal_url': 'https://secure.login.gov/', 'alt_note': None, 'info': 'Workforce alignment tracking infrastructure configuration. Action Item Required: Girish to Register / Enroll inside Login.gov engine workspace to finish overall backend programmatic verification sync.'},
    {'key': 'eftpsgov', 'num': 27, 'quarter': 'ROLL', 'scope': 'Federal', 'short': 'EFTPS Portal', 'title': 'Federal Tax Portal Access and PIN Security Profile', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Continuous account management.', 'entity': 'Bookr, Inc.', 'portal_name': 'www.eftps.gov', 'portal_url': 'https://secure.login.gov/', 'alt_note': None, 'info': 'IRS Federal Tax Payment Portal engine setup. Access metrics verification required. Action Item Required: Girish to complete official profile setup.'},
    {'key': 'coterie', 'num': 28, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Coterie Insurance', 'title': 'Coterie Insurance Renewal (Professional Liability)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — monitor operational window boundaries.', 'entity': 'Bookr, Inc.', 'portal_name': 'Coterie Policy Workspace', 'portal_url': 'https://mypolicycenter.coterieinsurance.com/signin', 'alt_note': None, 'info': 'Corporate commercial liability platform configuration, protecting professional code structures and client consultation assets.'},
    {'key': 'sterling', 'num': 29, 'quarter': 'ROLL', 'scope': 'Federal', 'short': 'Sterling HSA POP', 'title': 'Sterling HSA Premium Only Plan Corporate Compliance Check', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Continuous operational window monitoring status.', 'entity': 'Bookr, Inc.', 'portal_name': 'Sterling HSA Engine', 'portal_url': 'https://www.sterlinghsa.com/Accounts/Login/', 'alt_note': None, 'info': 'Premium Only Plan alignment checks mandated under IRS section code variables. Secured through Madeline King at Engers Benefit Group.'},
    {'key': 'anthem', 'num': 30, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Anthem Portal', 'title': 'Anthem Employer Health Insurance Premium Portal Management', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Monthly accounting pipeline reconciliations.', 'entity': 'Bookr, Inc.', 'portal_name': 'Anthem Employer Center', 'portal_url': 'https://employer.anthem.com/eea/public/login', 'alt_note': None, 'info': 'Core operational workspace hub for tracking state group health enrollment variables and employee eligibility metrics.'},
    {'key': 'hartford', 'num': 31, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Hartford Business', 'title': 'Hartford Insurance Policy Renewal (General Liability / Property)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — inspect coverage boundaries.', 'entity': 'Bookr, Inc.', 'portal_name': 'The Hartford Account Center', 'portal_url': 'https://account.thehartford.com/customer/login', 'alt_note': None, 'info': 'Primary operational business liability and physical property infrastructure safety matrix handling.'},
    {'key': 'travelers', 'num': 32, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Travelers Workers Comp', 'title': 'Travelers Worker’s Compensation Insurance Compliance Policy', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — monitor state insurance payroll audits.', 'entity': 'Bookr, Inc.', 'portal_name': 'Travelers Portal Engine', 'portal_url': 'https://signin.travelers.com/', 'alt_note': None, 'info': 'Statutory payroll worker safety policy mandated by the State of California matching team expansion records.'},
]


# ---------------------------------------------------------------------------
# Standard Non-Profit Framework
# Seeded when NAICS onboarding classifies the organization as a 501(c)(3) /
# non-profit entity (e.g. NAICS 813xxx — Religious, Grantmaking, Civic,
# Professional & Similar Organizations). Generic across states; entity-
# specific text ("State", "the state") is meant to be edited per org.
# ---------------------------------------------------------------------------
NON_PROFIT_TASKS = [
    {'key': 'np_990', 'num': 1, 'quarter': 'Q2', 'scope': 'Federal', 'short': 'Form 990', 'title': 'Return of Organization Exempt From Income Tax (Form 990 / 990-EZ / 990-N)', 'due_type': 'fixed', 'due_month': 5, 'due_day': 15, 'due_text': '15th day of the 5th month after fiscal year end (May 15 for calendar-year filers)', 'entity': 'Non-Profit', 'portal_name': 'IRS e-file (Modernized e-File)', 'portal_url': 'https://www.irs.gov/e-file-providers/exempt-organizations-modernized-e-file-mef', 'alt_note': 'A 6-month extension is available via Form 8868.', 'info': 'Annual informational return required of nearly all tax-exempt organizations. Form (990, 990-EZ, or 990-N postcard) depends on gross receipts and total assets. Failure to file for 3 consecutive years triggers automatic revocation of tax-exempt status.'},
    {'key': 'np_990t', 'num': 2, 'quarter': 'Q2', 'scope': 'Federal', 'short': 'Form 990-T', 'title': 'Exempt Organization Business Income Tax Return (Form 990-T)', 'due_type': 'fixed', 'due_month': 5, 'due_day': 15, 'due_text': 'Same deadline as Form 990', 'entity': 'Non-Profit', 'portal_name': 'IRS e-file (Modernized e-File)', 'portal_url': 'https://www.irs.gov/e-file-providers/exempt-organizations-modernized-e-file-mef', 'alt_note': None, 'info': 'Only required if the organization has $1,000+ of gross unrelated business taxable income (UBTI) from activity not substantially related to its exempt purpose.'},
    {'key': 'np_941', 'num': 3, 'quarter': 'Q1', 'scope': 'Federal', 'short': 'Form 941', 'title': 'Employer\u2019s Quarterly Federal Tax Return (Form 941)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 30, 'due_text': 'Last day of the month following each quarter', 'entity': 'Non-Profit', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Typically automated by payroll providers such as Gusto or ADP.', 'info': 'Reports federal income tax withholding and both employer/employee Social Security & Medicare tax. Required for any 501(c)(3) with W-2 staff, regardless of tax-exempt status.'},
    {'key': 'np_w2w3', 'num': 4, 'quarter': 'Q1', 'scope': 'Federal', 'short': 'W-2 / W-3', 'title': 'Wage and Tax Statements (Forms W-2 & W-3)', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Non-Profit', 'portal_name': 'SSA Business Services Online', 'portal_url': 'https://www.ssa.gov/bso', 'alt_note': None, 'info': 'Required for any organization with W-2 employees, exempt or not.'},
    {'key': 'np_1099nec', 'num': 5, 'quarter': 'Q1', 'scope': 'Federal', 'short': '1099-NEC', 'title': 'Form 1099-NEC Filing & Distribution', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'Non-Profit', 'portal_name': 'IRS FIRE System', 'portal_url': 'https://fire.irs.gov/', 'alt_note': None, 'info': 'Required if the organization paid any unincorporated contractor or consultant $600 or more in the prior calendar year.'},
    {'key': 'np_charity_reg', 'num': 6, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Charitable Solicitation Reg.', 'title': 'State Charitable Solicitation Registration', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — renewal window varies by state', 'entity': 'Non-Profit', 'portal_name': 'State Attorney General / Secretary of State Charities Portal', 'portal_url': None, 'alt_note': None, 'info': 'Most states require registration (and annual renewal) with the Attorney General or equivalent charities bureau before soliciting donations from residents. Multi-state fundraising may require registering in each state.'},
    {'key': 'np_ag_report', 'num': 7, 'quarter': 'ROLL', 'scope': 'State', 'short': 'AG Annual Financial Report', 'title': 'Attorney General Annual Charity Financial Report (e.g. RRF-1 or equivalent)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, tied to fiscal year end', 'entity': 'Non-Profit', 'portal_name': 'State Charities Bureau Portal', 'portal_url': None, 'alt_note': None, 'info': 'Separate from Form 990 — many states require their own annual financial disclosure to keep charitable registration active.'},
    {'key': 'np_soi', 'num': 8, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Annual/Biennial Report', 'title': 'Secretary of State Annual or Biennial Report (Statement of Information)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually or biennially — check state entity anniversary date', 'entity': 'Non-Profit', 'portal_name': 'Secretary of State Business Portal', 'portal_url': None, 'alt_note': None, 'info': 'Keeps the corporate entity in good standing with the state of incorporation; typically lists current officers/directors and registered agent.'},
    {'key': 'np_property_exempt', 'num': 9, 'quarter': 'Q2', 'scope': 'State', 'short': 'Property Tax Exemption Filing', 'title': 'Welfare / Property Tax Exemption Renewal Claim', 'due_type': 'fixed', 'due_month': 4, 'due_day': 1, 'due_text': 'Typically April 1, varies by county/state', 'entity': 'Non-Profit', 'portal_name': 'County Assessor Portal', 'portal_url': None, 'alt_note': None, 'info': 'Only applicable if the organization owns real or personal property and claims a charitable/welfare exemption from local property tax.'},
    {'key': 'np_regagent', 'num': 10, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Registered Agent', 'title': 'Registered Agent Annual Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, on the service provider\u2019s contract anniversary', 'entity': 'Non-Profit', 'portal_name': 'Registered Agent Service Portal', 'portal_url': None, 'alt_note': None, 'info': 'Non-payment causes the registered agent to resign, which can put the entity out of good standing.'},
    {'key': 'np_donor_ack', 'num': 11, 'quarter': 'Q1', 'scope': 'Internal', 'short': 'Donor Acknowledgment Letters', 'title': 'Annual Contemporaneous Written Acknowledgment for Donors', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Issued for gifts of $250+ as they are received; reconciled annually', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'IRS requires a written acknowledgment for any single contribution of $250 or more before the donor can claim a deduction.'},
    {'key': 'np_board_minutes', 'num': 12, 'quarter': 'ROLL', 'scope': 'Internal', 'short': 'Board Meeting Minutes', 'title': 'Annual Board of Directors Meeting & Minute Book Update', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'At least once annually, per bylaws', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Preserves the corporate/governance record and satisfies bylaw requirements for board oversight of a 501(c)(3).'},
    {'key': 'np_coi_policy', 'num': 13, 'quarter': 'ROLL', 'scope': 'Internal', 'short': 'Conflict of Interest Disclosures', 'title': 'Annual Conflict of Interest Policy Disclosure (Board & Key Staff)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Form 990 asks whether the organization has and enforces a written conflict-of-interest policy; annual signed disclosures document compliance.'},
    {'key': 'np_do_ins', 'num': 14, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'D&O Insurance', 'title': 'Directors & Officers Liability Insurance Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Protects board members and officers from personal liability arising from governance decisions.'},
    {'key': 'np_gl_ins', 'num': 15, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'General Liability Insurance', 'title': 'General Liability Insurance Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Covers third-party bodily injury/property damage claims arising from programs, events, or the organization\u2019s premises.'},
    {'key': 'np_wc_ins', 'num': 16, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Workers\u2019 Compensation', 'title': 'Workers\u2019 Compensation Insurance Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'Non-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Statutory requirement in most states once the organization has W-2 employees, exempt status notwithstanding.'},
]


# ---------------------------------------------------------------------------
# Standard For-Profit Framework
# Seeded when NAICS onboarding classifies the organization as a standard
# for-profit corporation / LLC that is NOT the Bookr internal entity
# (NAICS 541511). Generic across states.
# ---------------------------------------------------------------------------
FOR_PROFIT_TASKS = [
    {'key': 'fp_1120', 'num': 1, 'quarter': 'Q2', 'scope': 'Federal', 'short': 'Form 1120', 'title': 'U.S. Corporation Income Tax Return (Form 1120)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'April 15 (calendar-year filers)', 'entity': 'For-Profit', 'portal_name': 'EFTPS (payment)', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Can be extended 6 months to October 15 via Form 7004.', 'info': 'Core federal income tax return for a C-corporation. (Pass-through entities such as S-corps or LLCs file Form 1120-S or the partnership return instead.)'},
    {'key': 'fp_1120w', 'num': 2, 'quarter': 'ROLL', 'scope': 'Federal', 'short': 'Est. Tax (1120-W)', 'title': 'Federal Quarterly Estimated Income Tax (Form 1120-W)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Apr 15 / Jun 15 / Sep 15 / Dec 15', 'entity': 'For-Profit', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Required once the corporation anticipates $500+ of annual federal income tax liability. Four installments across the fiscal year.'},
    {'key': 'fp_941', 'num': 3, 'quarter': 'Q1', 'scope': 'Federal', 'short': 'Form 941', 'title': 'Employer\u2019s Quarterly Federal Tax Return (Form 941)', 'due_type': 'fixed', 'due_month': 4, 'due_day': 30, 'due_text': 'Last day of the month following each quarter', 'entity': 'For-Profit', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': 'Typically automated by payroll providers such as Gusto or ADP.', 'info': 'Reconciles federal income tax withholding plus Social Security and Medicare tax for the quarter.'},
    {'key': 'fp_940', 'num': 4, 'quarter': 'Q1', 'scope': 'Federal', 'short': '940 FUTA', 'title': 'Federal Annual Unemployment Tax Return (Form 940)', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'For-Profit', 'portal_name': 'EFTPS', 'portal_url': 'https://www.eftps.gov/eftps/', 'alt_note': None, 'info': 'Assesses FUTA liability on the first $7,000 paid to each W-2 employee for the year.'},
    {'key': 'fp_w2w3', 'num': 5, 'quarter': 'Q1', 'scope': 'Federal', 'short': 'W-2 / W-3', 'title': 'Wage and Tax Statements (Forms W-2 & W-3)', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'For-Profit', 'portal_name': 'SSA Business Services Online', 'portal_url': 'https://www.ssa.gov/bso', 'alt_note': None, 'info': 'Required for any employer with W-2 staff.'},
    {'key': 'fp_1099nec', 'num': 6, 'quarter': 'Q1', 'scope': 'Federal', 'short': '1099-NEC', 'title': 'Form 1099-NEC Filing & Distribution', 'due_type': 'fixed', 'due_month': 1, 'due_day': 31, 'due_text': 'January 31', 'entity': 'For-Profit', 'portal_name': 'IRS FIRE System', 'portal_url': 'https://fire.irs.gov/', 'alt_note': None, 'info': 'Required if the company paid an unincorporated contractor $600 or more in the prior calendar year.'},
    {'key': 'fp_state_income_tax', 'num': 7, 'quarter': 'Q2', 'scope': 'State', 'short': 'State Corporate Tax Return', 'title': 'State Corporate Franchise & Income Tax Return', 'due_type': 'fixed', 'due_month': 4, 'due_day': 15, 'due_text': 'Typically April 15, aligned with the federal return', 'entity': 'For-Profit', 'portal_name': 'State Dept. of Revenue / Franchise Tax Board Portal', 'portal_url': None, 'alt_note': None, 'info': 'Most states levy their own corporate income or franchise tax, often including a minimum tax owed regardless of profitability.'},
    {'key': 'fp_state_est_tax', 'num': 8, 'quarter': 'ROLL', 'scope': 'State', 'short': 'State Est. Tax', 'title': 'State Corporate Estimated Tax Installments', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Quarterly, per state schedule', 'entity': 'For-Profit', 'portal_name': 'State Dept. of Revenue Portal', 'portal_url': None, 'alt_note': None, 'info': 'Quarterly prepayments toward the state\u2019s annual corporate tax liability.'},
    {'key': 'fp_state_payroll', 'num': 9, 'quarter': 'Q1', 'scope': 'State', 'short': 'State Payroll Tax Returns', 'title': 'State Quarterly Payroll / Unemployment Insurance Returns', 'due_type': 'fixed', 'due_month': 4, 'due_day': 30, 'due_text': 'Last day of the month following each quarter', 'entity': 'For-Profit', 'portal_name': 'State Employment Development / Workforce Agency Portal', 'portal_url': None, 'alt_note': None, 'info': 'Reports state income tax withholding and state unemployment/disability insurance contributions.'},
    {'key': 'fp_soi', 'num': 10, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Annual Report / SOI', 'title': 'Annual Report / Statement of Information', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, on the entity\u2019s state anniversary date', 'entity': 'For-Profit', 'portal_name': 'Secretary of State Business Portal', 'portal_url': None, 'alt_note': None, 'info': 'Keeps the entity in good standing with its state(s) of formation/qualification; typically lists current officers/directors and registered agent. Missing it can trigger penalties or administrative dissolution.'},
    {'key': 'fp_regagent', 'num': 11, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Registered Agent', 'title': 'Registered Agent Annual Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, on the service provider\u2019s contract anniversary', 'entity': 'For-Profit', 'portal_name': 'Registered Agent Service Portal', 'portal_url': None, 'alt_note': None, 'info': 'Non-payment causes the registered agent to resign, jeopardizing good standing.'},
    {'key': 'fp_biz_license', 'num': 12, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Business License', 'title': 'Local Business License / Tax Certificate Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually, before expiration', 'entity': 'For-Profit', 'portal_name': 'City/County Business License Portal', 'portal_url': None, 'alt_note': None, 'info': 'Required by most cities/counties to legally operate at a given location; late renewal often carries a percentage penalty.'},
    {'key': 'fp_sales_tax', 'num': 13, 'quarter': 'ROLL', 'scope': 'State', 'short': 'Sales & Use Tax', 'title': 'Sales & Use Tax Return', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Monthly, quarterly, or annually depending on sales volume', 'entity': 'For-Profit', 'portal_name': 'State Dept. of Revenue Portal', 'portal_url': None, 'alt_note': None, 'info': 'Only applicable if the company sells taxable goods/services and has nexus in the state.'},
    {'key': 'fp_boi', 'num': 14, 'quarter': 'ROLL', 'scope': 'Federal', 'short': 'BOI Report', 'title': 'Beneficial Ownership Information Report (FinCEN)', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Within 30 days of formation; updates within 30 days of any change', 'entity': 'For-Profit', 'portal_name': 'FinCEN BOI E-Filing System', 'portal_url': 'https://boiefiling.fincen.gov/', 'alt_note': None, 'info': 'Reports individuals who directly or indirectly own/control the company, per the Corporate Transparency Act. Confirm current applicability and exemptions, as reporting requirements have been in flux.'},
    {'key': 'fp_formalities', 'num': 15, 'quarter': 'ROLL', 'scope': 'Internal', 'short': 'Corp Formalities', 'title': 'Mandatory Annual Corporate Formalities', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually — best practice within 5 months of fiscal year close', 'entity': 'For-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Execute Unanimous Written Consents (or hold formal meetings) for shareholders/members and directors; store in the corporate minute book to preserve the entity\u2019s liability shield.'},
    {'key': 'fp_gl_ins', 'num': 16, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'General Liability Insurance', 'title': 'General Liability / Business Insurance Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'For-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Covers third-party bodily injury and property damage claims arising from business operations.'},
    {'key': 'fp_wc_ins', 'num': 17, 'quarter': 'ROLL', 'scope': 'Insurance', 'short': 'Workers\u2019 Compensation', 'title': 'Workers\u2019 Compensation Insurance Renewal', 'due_type': 'rolling', 'due_month': None, 'due_day': None, 'due_text': 'Annually', 'entity': 'For-Profit', 'portal_name': None, 'portal_url': None, 'alt_note': None, 'info': 'Statutory requirement in most states once the company has W-2 employees.'},
]
